# Site settings
title: MTN Group API Documentation
email: developer@mtn.com
description: >
  Documentation for MTN's public API.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: https://mtn-group.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/MTN-Group/MTN-Group.github.io
git_edit_address: https://github.com/MTN-Group/MTN-Group.github.io/blob/gh-pages

# Theme options from https://bootswatch.com/
# comment-out to use default Bootstrap
bootwatch: flatly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: US/Eastern
defaults:

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _about
    type: about
  values:
    layout: about
    sectionid: about

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  about:
    permalink: /:collection/:path/
    output: true
